_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/main.py
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 32
ckpt_path:
    value: null
debug:
    value: false
dropped_class:
    value: null
epochs:
    value: 1000
eval_batch_size:
    value: 1
exp_dir:
    value: /home/diane.kim/nature/scripts/checkpoint/2025-09-01_19-21-39
exp_name:
    value: treatnet
freeze:
    value: false
learning_rate:
    value: 0.0001
loss_fn:
    value: ce
lpft:
    value: false
mode:
    value: late_fusion
multitask:
    value: false
nhead:
    value: 4
no_wandb:
    value: false
non_balanced_batch:
    value: false
num_layers:
    value: 2
num_workers:
    value: 0
optim:
    value: sgd
prefix:
    value: ""
pretrain_epochs:
    value: 10
pretrain_view:
    value: false
save_embeddings:
    value: false
seed:
    value: 0
subsample_frac:
    value: null
subsample_n:
    value: null
suffix:
    value: ""
tab_weight:
    value: /home/diane.kim/nature/baseline/tabpfn_mlp/checkpoints/tabweights_final_epoch_seed15_best.pt
target:
    value: tp
total_epochs:
    value: 50
unfreeze_encoder:
    value: false
use_view_tokens:
    value: false
wdb_group:
    value: 2262_wTTE_v1.1c
weight_decay:
    value: 0.01
